PROJECT_PATH = "D:/Acads/Projects/Identity Detection/face_recognition_system"
#PROJECT_PATH = "/home/avinash/Desktop/Projects/face-recognition-attendance-system"
PATH = PROJECT_PATH+"/static/data"
STORAGE_PATH = PROJECT_PATH+"/storage"
LANDMARK_PATH = PROJECT_PATH+"/storage/shape_predictor_68_face_landmarks.dat"